### ISSUE TITLE
Found an Error.

### ISSUE THREAD

**Issue by simpleann** [akashprojects/PHP-CMS#1]
Hi I like to try your work, I think it will help me to understand how laravel works.
I installed it to my local and follow the directions in readme.md.
And it throws Error:

Parse error: syntax error, unexpected 'yield' (T_YIELD), expecting '(' in C:\xampp\htdocs\PHP-CMS-master\laravel\helpers.php on line 560

How will I resolve it. Any idea will be appreciated. Thanks in advance.

**Comment by ghost** [comment]
I found solution in this link http://laravel.io/forum/02-08-2014-transferred-my-laravel-app-from-one-server-to-another-i-have-a-problem
